{
 "title": "PulseNet Microservices Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=~\"4..|5..\"}[1m])) / sum(rate(http_request_duration_seconds_count[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (service) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response Latency p95 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, service) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{service}} - p95"
    }
   ]
  }
 ]
}